import Foundation
import WiFiCore

@MainActor func L(_ key: String, _ arguments: String...) -> String {
    let language = AppSettings.shared.language.resolved
    let index = language == "zh" ? 1 : 0
    var text = descriptions[key]?[language == "ko" ? 0 : language == "en" ? 1 : 2] ?? (language == "ko" ? key : translations[key]?[index] ?? key)
    if key == "제조사 안내 {0}" && language == "ko" {
        text = "제조사는 IEEE MAC 주소 등록기관으로 실제 기기 브랜드와 다를 수 있습니다. 로컬 관리 주소는 추정하지 않습니다. 데이터 기준: {0}."
    }
    for (index, value) in arguments.enumerated() { text = text.replacingOccurrences(of: "{\(index)}", with: value) }
    return text
}
@MainActor func manufacturerLabel(_ info: ManufacturerInfo) -> String { info.organization ?? L(info.label) }

private let translations: [String: [String]] = [
    "선택한 네트워크 어댑터를 찾을 수 없습니다. 설정에서 어댑터를 다시 선택하세요.": ["The selected network adapter is unavailable. Choose another adapter in Settings.", "所选网络适配器不可用。请在设置中重新选择适配器。"],
    "대역 · 채널 · 폭": ["Band · Channel · Width", "频段 · 信道 · 带宽"],
    "시간": ["Time", "时间"],
    "{0} 채널 분포. {1}개 AP. 네트워크 목록에서도 선택할 수 있습니다.": ["{0} channel distribution. {1} APs. You can also select from the network list.", "{0} 信道分布。{1} 个接入点。也可在网络列表中选择。"],
    "암호화 없음": ["Unencrypted", "未加密"],
    "현재 목록에서 관측": ["In the current list", "当前列表"],
    "Wi-Fi 인터페이스를 찾을 수 없습니다. Wi-Fi 어댑터 연결 상태를 확인하세요.": ["No Wi-Fi adapter found. Check the adapter connection.", "未找到 Wi-Fi 适配器。请检查适配器连接。"],
    "Wi-Fi가 꺼져 있습니다. 시스템 설정에서 Wi-Fi를 켠 후 다시 스캔하세요.": ["Wi-Fi is off. Turn it on in System Settings and scan again.", "Wi-Fi 已关闭。请在系统设置中打开 Wi-Fi 后重新扫描。"],
    "스캔 결과가 없습니다. 위치 서비스와 Wi-Fi 상태를 확인하고 다시 시도하세요.": ["No scan results. Check location access and Wi-Fi, then try again.", "没有扫描结果。请检查位置权限和 Wi-Fi 状态后重试。"],
    "개요": ["Overview", "概览"],
    "네트워크": ["Networks", "网络"],
    "신호 이력": ["Signal history", "信号历史"],
    "원시 데이터": ["Raw data", "原始数据"],
    "워크스페이스": ["Workspaces", "工作区"],
    "Wi-Fi 분석": ["Wi-Fi Analyzer", "Wi-Fi 分析"],
    "설정": ["Settings", "设置"],
    "완료": ["Done", "完成"],
    "적용": ["Apply", "应用"],
    "취소": ["Cancel", "取消"],
    "저장": ["Save", "保存"],
    "저장 중…": ["Saving…", "正在保存…"],
    "열기": ["Open", "打开"],
    "이름": ["Name", "名称"],
    "목록 저장": ["Save list", "保存列表"],
    "내보내기": ["Export", "导出"],
    "지금 스캔": ["Scan now", "立即扫描"],
    "스캔 중…": ["Scanning…", "正在扫描…"],
    "일시 정지": ["Pause", "暂停"],
    "다시 시작": ["Resume", "继续"],
    "네트워크 어댑터": ["Network adapter", "网络适配器"],
    "자동 선택": ["Automatic", "自动选择"],
    "스캔 간격": ["Scan interval", "扫描间隔"],
    "{0}초": ["{0} sec", "{0} 秒"],
    "숨겨진 네트워크": ["Hidden networks", "隐藏网络"],
    "스캔에 포함": ["Include in scan", "扫描时包含"],
    "언어": ["Language", "语言"],
    "화면 모드": ["Appearance", "外观"],
    "시스템 설정에 따름": ["Follow system settings", "跟随系统设置"],
    "라이트 모드": ["Light", "浅色模式"],
    "다크 모드": ["Dark", "深色模式"],
    "스캔 설정은 적용을 누르면 반영됩니다.": ["Scan settings take effect when you click Apply.", "点击“应用”后，扫描设置将生效。"],
    "데모 모드": ["Sample data", "示例数据"],
    "샘플 데이터": ["Sample data", "示例数据"],
    "네트워크와 측정값은 샘플 데이터입니다.": ["The networks and measurements shown are samples.", "当前显示的网络和测量值均为示例数据。"],
    "실제 Wi-Fi로 전환": ["Switch to live Wi-Fi", "切换到实时 Wi-Fi"],
    "실시간 측정으로 돌아가기": ["Return to live scanning", "返回实时扫描"],
    "저장된 목록": ["Saved list", "已保存的列表"],
    "Wi-Fi 이름 조회를 위한 위치 접근": ["Location access for Wi-Fi names", "访问 Wi-Fi 名称需要位置权限"],
    "SSID와 BSSID를 읽는 데 필요합니다. 위치 좌표는 수집하지 않습니다.": ["Required to read SSIDs and BSSIDs. Location coordinates are not collected.", "读取 SSID 和 BSSID 需要此权限。应用不会收集位置坐标。"],
    "권한 허용": ["Allow access", "允许访问"],
    "위치 설정 열기": ["Open Location Settings", "打开定位设置"],
    "측정 안내": ["Measurement notice", "测量提示"],
    "닫기": ["Dismiss", "关闭"],
    "JSON · 원시 데이터와 이력": ["JSON · Raw data and history", "JSON · 原始数据和历史"],
    "CSV · 현재 네트워크 목록": ["CSV · Current network list", "CSV · 当前网络列表"],
    "자동 측정 정지 / 시작 · ⌘P": ["Pause / resume scanning · ⌘P", "暂停 / 继续扫描 · ⌘P"],
    "채널 분포": ["Channel distribution", "信道分布"],
    "주변 AP가 사용하는 주파수와 신호 세기를 함께 살펴보세요.": ["Frequencies and signal levels of nearby access points.", "附近接入点的频率和信号强度。"],
    "네트워크 보기": ["View networks", "查看网络"],
    "신호 분석": ["Signal analysis", "信号分析"],
    "선택한 네트워크의 측정값을 바탕으로 분석합니다.": ["Based on measurements of the selected network.", "根据所选网络的测量数据进行分析。"],
    "상세 정보 보기": ["View details", "查看详情"],
    "선택한 네트워크": ["Selected network", "所选网络"],
    "다른 네트워크 살펴보기": ["Browse networks", "浏览网络"],
    "채널 {0}": ["Channel {0}", "信道 {0}"],
    "채널 폭 미확인": ["Width unavailable", "带宽未知"],
    "데모 살펴보기": ["View sample data", "查看示例数据"],
    "주변 네트워크": ["Nearby networks", "附近网络"],
    "현재 스캔에서 관측": ["Observed in the latest scan", "最近一次扫描结果"],
    "신호 대 잡음비": ["Signal-to-noise ratio", "信噪比"],
    "선택 AP의 RSSI − noise": ["Selected AP: RSSI − noise", "所选接入点：RSSI − noise"],
    "현재 연결 Tx rate": ["Current Tx rate", "当前发送速率"],
    "Mac의 PHY 링크 속도": ["Link rate, not throughput", "链路速率，非实际吞吐量"],
    "{0}개 네트워크": ["{0} networks", "{0} 个网络"],
    "{0}개 표시": ["{0} shown", "显示 {0} 个"],
    "전체": ["All", "全部"],
    "모든 보안": ["All security types", "所有安全类型"],
    "보안 설정됨": ["Secured", "已加密"],
    "보안": ["Security", "安全"],
    "이름, 제조사, BSSID 검색": ["Name, manufacturer, BSSID", "名称、制造商、BSSID"],
    "검색 지우기": ["Clear search", "清除搜索"],
    "행을 선택하면 개요·이력·원시 데이터에 반영됩니다.": ["Selection applies to overview, history and raw data.", "选择结果会同步到概览、历史和原始数据。"],
    "선택 AP 상세": ["Selected AP details", "所选接入点详情"],
    "제조사": ["Manufacturer", "制造商"],
    "채널": ["Channel", "信道"],
    "폭": ["Width", "带宽"],
    "대역": ["Band", "频段"],
    "네트워크를 선택하세요": ["Select a network", "请选择网络"],
    "네트워크 선택": ["Select network", "选择网络"],
    "신호 이력 보기": ["View signal history", "查看信号历史"],
    "원시 데이터 보기": ["View raw data", "查看原始数据"],
    "RSSI와 noise의 변화를 시간에 따라 확인하세요.": ["RSSI and noise measurements over time.", "查看 RSSI 和噪声随时间的变化。"],
    "비콘과 프로브 응답의 Information Element를 직접 읽습니다.": ["Information elements from beacon and probe responses.", "信标和探测响应中的信息元素。"],
    "선택한 AP": ["Selected AP", "所选接入点"],
    "원본 크기": ["Raw size", "原始大小"],
    "제조사 · IEEE 등록기관": ["Manufacturer · IEEE registrant", "制造商 · IEEE 注册机构"],
    "자동 측정 · {0}초 간격": ["Automatic scanning · Every {0} sec", "自动扫描 · 每 {0} 秒"],
    "마지막 스캔 {0}": ["Last scan {0}", "上次扫描 {0}"],
    "신호 측정 대기": ["Waiting for signal", "等待测量信号"],
    "매우 좋음": ["Excellent", "极好"],
    "좋음": ["Good", "良好"],
    "보통": ["Fair", "一般"],
    "약함": ["Weak", "较弱"],
    "측정 없음": ["Unavailable", "无测量值"],
    "로컬 관리 주소": ["Locally administered", "本地管理地址"],
    "그룹 주소": ["Group address", "组地址"],
    "등록기관 미확인": ["Unregistered / unknown", "未注册 / 未知"],
    "주소 미제공": ["Address unavailable", "地址不可用"],
    "등록 데이터 없음": ["Registry unavailable", "注册数据不可用"],
    "{0} 설명": ["About {0}", "关于 {0}"],
    "워크스페이스에 저장": ["Save to workspace", "保存到工作区"],
    "현재 필터가 적용된 {0}개 네트워크와 신호 이력을 저장합니다.": ["Save the {0} currently filtered networks and their signal history.", "保存当前筛选的 {0} 个网络及其信号历史。"],
    "저장한 네트워크 목록과 이력을 다시 엽니다.": ["Open saved network lists and signal history.", "打开已保存的网络列表和信号历史。"],
    "저장한 목록이 없습니다": ["No saved lists", "没有已保存的列表"],
    "네트워크 화면의 목록 저장 버튼으로 현재 목록을 저장하세요.": ["Use Save list to keep the networks currently shown.", "点击“保存列表”即可保存当前显示的网络。"],
    "스캔을 기다리고 있습니다": ["Waiting for a scan", "等待扫描"],
    "검색 결과가 없습니다": ["No results", "没有搜索结果"],
    "위치 권한과 Wi-Fi 상태를 확인하세요.": ["Check location access and Wi-Fi status.", "请检查位置权限和 Wi-Fi 状态。"],
    "검색어 또는 대역과 보안 필터를 변경해 보세요.": ["Change the search, band or security filter.", "请更改搜索条件、频段或安全筛选条件。"],
    "IE 이름, ID, 해석 내용 검색": ["Search IE name, ID or decoded value", "搜索 IE 名称、ID 或解析内容"],
    "보기 방식": ["View", "视图"],
    "해석된 IE": ["Decoded IEs", "解析后的 IE"],
    "전체 Hex": ["Full hex", "完整十六进制"],
    "복사됨": ["Copied", "已复制"],
    "Hex 복사": ["Copy hex", "复制十六进制"],
    "길이": ["Length", "长度"],
    "해석": ["Decoded value", "解析内容"],
    "미해석 IE": ["Undecoded IE", "未解析的 IE"],
    "일치하는 Information Element가 없습니다.": ["No matching information elements.", "没有匹配的信息元素。"],
    "원시 데이터가 없습니다": ["No raw data", "没有原始数据"],
    "macOS가 제공한 Information Element만 표시합니다.": ["Only information elements returned by macOS are shown.", "仅显示 macOS 返回的信息元素。"],
    "네트워크 상세": ["Network details", "网络详情"],
    "주소 할당": ["Address assignment", "地址分配"],
    "원본 SSID bytes": ["Raw SSID bytes", "原始 SSID 字节"],
    "국가": ["Country", "国家或地区"],
    "보안 판별 근거": ["Security evidence", "安全类型依据"],
    "원본 RSSI / noise": ["Raw RSSI / noise", "原始 RSSI / 噪声"],
    "AP 보고 접속 기기 수": ["AP-reported station count", "接入点报告的设备数"],
    "Primary 주파수": ["Primary frequency", "主信道频率"],
    "관측 시각": ["Observed at", "观测时间"],
    "제공되지 않음": ["Unavailable", "未提供"],
    "미확인": ["Unknown", "未知"],
    "BSS Load IE 없음": ["No BSS Load IE", "无 BSS Load IE"],
    "원시 RSN / WPA IE": ["Advertised RSN / WPA information", "广播的 RSN / WPA 信息"],
    "주변 AP": ["Nearby APs", "附近接入点"],
    "그래프 대역": ["Chart band", "图表频段"],
    "채널 폭과 RSSI로 그린 분포입니다. RF 스펙트럼 실측이 아니며, 폭이 미확인된 AP는 점선으로 표시합니다.": ["Modeled from channel width and RSSI, not a measured RF spectrum. Dashed lines indicate unknown widths.", "根据信道带宽和 RSSI 绘制，并非实际射频频谱。虚线表示未知带宽。"],
    "관측된 네트워크 없음": ["No networks observed", "未发现网络"],
    "측정": ["Measurement", "测量"],
    "AP 스캔": ["AP scan", "接入点扫描"],
    "연결 링크": ["Connected link", "当前连接"],
    "기간": ["Time range", "时间范围"],
    "1분": ["1 min", "1 分钟"],
    "5분": ["5 min", "5 分钟"],
    "15분": ["15 min", "15 分钟"],
    "신호 이력을 기다립니다": ["Waiting for signal history", "等待信号历史"],
    "연결 링크는 현재 Mac이 연결한 AP에서만 측정합니다.": ["Link measurements are available only for the AP connected to this Mac.", "链路测量仅适用于此 Mac 当前连接的接入点。"],
    "선택한 AP의 스캔이 완료되면 여기에 기록됩니다.": ["Measurements appear when a scan of the selected AP completes.", "所选接入点的扫描完成后，测量值将显示在此处。"],
    "최대 15분 보관 · dBm": ["Up to 15 minutes · dBm", "最多保留 15 分钟 · dBm"],
    "{0}개 표본": ["{0} samples", "{0} 个样本"],
    "연결 AP / 1초 폴링": ["Connected AP / 1 sec polling", "当前接入点 / 每秒采样"],
    "주변 AP / 스캔 완료 시 기록": ["Nearby AP / recorded after each scan", "附近接入点 / 每次扫描后记录"],
    "신호 분석 대기": ["Waiting for analysis", "等待分析"],
    "네트워크를 선택하면 신호 세기, 채널 중첩과 보안 정보를 분석합니다.": ["Select a network to analyze signal, channel overlap and security.", "选择网络以分析信号、信道重叠和安全信息。"],
    "제조사 안내 {0}": ["Manufacturer means the IEEE MAC address registrant. It may differ from the device brand. Locally administered addresses are not inferred. Registry updated: {0}.", "制造商指 IEEE MAC 地址注册机构，可能与设备品牌不同。不会推断本地管理地址的制造商。数据更新日期：{0}。"],
    "스캔": ["Scan", "扫描"],
    "JSON 세션 내보내기…": ["Export JSON session…", "导出 JSON 会话…"],
    "CSV 스캔 내보내기…": ["Export CSV scan…", "导出 CSV 扫描…"]
]

@MainActor func networkTitle(_ network: NetworkRecord) -> String {
    if let ssid = network.ssid, !ssid.isEmpty { return ssid }
    return L(network.name)
}
@MainActor func findingText(_ finding: Finding) -> (title: String, detail: String) {
    var key = "finding." + finding.id
    if finding.id == "signal" || finding.id == "snr" { key += finding.severity == .warning ? ".warning" : ".good" }
    func format(_ template: String) -> String {
        var text = L(template)
        for (index, value) in finding.values.enumerated() { text = text.replacingOccurrences(of: "{\(index)}", with: value) }
        return text
    }
    return (format(key + ".title"), format(key + ".detail"))
}

private let descriptions: [String: [String]] = [
    "term.RSSI": ["수신 신호의 세기입니다. 단위는 dBm이며 −40처럼 0에 가까울수록 강합니다. −80처럼 더 작은 값은 약한 신호입니다. 0은 측정 불가로 표시합니다.", "Received signal strength in dBm. A value closer to zero, such as −40, is stronger than −80. A returned value of 0 is treated as unavailable.", "接收信号强度，单位为 dBm。数值越接近 0，信号越强，例如 −40 强于 −80。返回 0 时视为无法测量。"],
    "term.Noise": ["수신 환경의 잡음 수준입니다. 단위는 dBm이며 더 낮은 값일수록 잡음이 적습니다. AP별 패킷에서 직접 측정한 잡음은 아닙니다.", "Estimated noise floor in dBm. Lower values indicate less noise. This is not a per-packet measurement from each access point.", "估计的背景噪声，单位为 dBm。数值越低，噪声越小。这并非针对每个接入点逐包测量的结果。"],
    "term.SNR": ["신호 대 잡음비입니다. RSSI에서 Noise를 뺀 값이며 단위는 dB입니다. 값이 클수록 신호를 잡음과 구분하기 쉽습니다. 두 측정값이 유효할 때만 계산합니다.", "Signal-to-noise ratio: RSSI minus Noise, in dB. Higher values mean the signal is easier to distinguish from noise. Calculated only when both readings are valid.", "信噪比，即 RSSI 减去 Noise，单位为 dB。数值越大，信号越容易与噪声区分。仅在两个读数均有效时计算。"],
    "term.Tx rate": ["현재 Mac 연결의 무선 링크 전송률입니다. 단위는 Mbps이며 인터넷 속도나 실제 데이터 처리량이 아닙니다.", "The wireless link transmission rate of this Mac's current connection, in Mbps. It is not internet speed or actual data throughput.", "此 Mac 当前无线连接的链路发送速率，单位为 Mbps。它并不代表互联网速度或实际数据吞吐量。"],
    "term.Manufacturer": ["BSSID의 주소 할당을 IEEE 등록 자료와 대조한 기관 이름입니다. 실제 기기 브랜드와 다를 수 있습니다. 로컬 관리 주소는 추정하지 않습니다.", "The organization registered for this BSSID's MAC address block with IEEE. It may differ from the device brand. Locally administered addresses are not inferred.", "根据 IEEE 注册资料查得的 BSSID 地址分配机构名称，可能与设备品牌不同。不会推断本地管理地址的制造商。"],
    "term.Channel": ["AP가 사용하는 주 채널 번호입니다. 같은 번호라도 2.4·5·6 GHz 대역에 따라 실제 주파수가 다릅니다.", "The AP's primary channel number. The same number can mean different frequencies in the 2.4, 5 and 6 GHz bands.", "接入点使用的主信道编号。相同编号在 2.4、5 和 6 GHz 频段中可能对应不同频率。"],
    "term.Width": ["AP가 사용하는 채널의 폭입니다. 단위는 MHz입니다. 폭이 넓으면 더 많은 주파수를 사용하며, 주변 AP와 겹칠 수 있습니다.", "Channel bandwidth in MHz. A wider channel uses more spectrum and can overlap more nearby access points.", "信道带宽，单位为 MHz。更宽的信道会占用更多频谱，也可能与更多附近接入点重叠。"],
    "finding.signal.good.title": ["양호한 신호 세기", "Good signal strength", "信号强度良好"],
    "finding.signal.good.detail": ["RSSI {0} dBm. 현재 위치에서 수신 신호가 양호합니다. 경험적 기준으로 평가합니다.", "RSSI {0} dBm. Reception is good at this location, based on an empirical threshold.", "RSSI 为 {0} dBm。根据经验阈值，当前位置的接收信号良好。"],
    "finding.signal.warning.title": ["약한 신호 세기", "Weak signal strength", "信号较弱"],
    "finding.signal.warning.detail": ["RSSI {0} dBm. AP에 가까운 위치에서 다시 측정해 보세요. 경험적 기준으로 평가합니다.", "RSSI {0} dBm. Try measuring closer to the AP. This assessment uses an empirical threshold.", "RSSI 为 {0} dBm。请尝试靠近接入点重新测量。此评估采用经验阈值。"],
    "finding.snr.good.title": ["충분한 신호 대 잡음비", "Good signal-to-noise ratio", "信噪比较好"],
    "finding.snr.warning.title": ["작은 신호 대 잡음비", "Low signal-to-noise ratio", "信噪比较低"],
    "finding.snr.good.detail": ["SNR {0} dB. RSSI와 Noise의 차이입니다. 이 앱은 20 dB 미만을 주의 기준으로 사용합니다.", "SNR {0} dB, the difference between RSSI and Noise. This app flags values below 20 dB.", "SNR 为 {0} dB，即 RSSI 与 Noise 的差值。此应用将低于 20 dB 的值标记为需注意。"],
    "finding.snr.warning.detail": ["SNR {0} dB. RSSI와 Noise의 차이입니다. 이 앱은 20 dB 미만을 주의 기준으로 사용합니다.", "SNR {0} dB, the difference between RSSI and Noise. This app flags values below 20 dB.", "SNR 为 {0} dB，即 RSSI 与 Noise 的差值。此应用将低于 20 dB 的值标记为需注意。"],
    "finding.overlap.title": ["채널이 겹치는 AP {0}개", "{0} overlapping APs", "{0} 个信道重叠的接入点"],
    "finding.overlap.detail": ["−85 dBm보다 강한 AP의 채널 범위가 겹칩니다. AP 수는 실제 혼잡도나 간섭 측정값이 아닙니다.", "These APs are stronger than −85 dBm and share channel spectrum. AP count is not a measurement of congestion or interference.", "这些接入点的信号强于 −85 dBm，且信道频谱重叠。接入点数量并不代表实际拥塞或干扰程度。"],
    "finding.load.title": ["AP 보고 채널 사용률 {0}%", "AP-reported utilization: {0}%", "接入点报告的信道利用率：{0}%"],
    "finding.load.detail": ["AP가 보고한 BSS Load 값입니다. 이 Mac에서 측정한 사용률은 아닙니다.", "Reported by the AP in its BSS Load information. Not utilization measured by this Mac.", "此数据由接入点通过 BSS Load 信息报告，并非此 Mac 测得的利用率。"],
    "finding.security.title": ["보안 설정 확인", "Review security settings", "请检查安全设置"],
    "finding.security.detail": ["{0}로 광고합니다. 관리하는 AP라면 WPA2-AES 또는 WPA3 설정을 확인하세요.", "Advertises {0}. For an AP you manage, review WPA2-AES or WPA3 settings.", "广播的安全类型为 {0}。如果您管理此接入点，请检查 WPA2-AES 或 WPA3 设置。"],
    "finding.variation.title": ["큰 신호 변동", "Signal variation", "信号波动较大"],
    "finding.variation.detail": ["최근 {0}회 스캔의 RSSI 표준편차는 {1} dB입니다. 위치나 무선 환경의 변화를 확인하세요.", "RSSI standard deviation is {1} dB over the last {0} scans. Check for changes in position or the radio environment.", "最近 {0} 次扫描的 RSSI 标准差为 {1} dB。请检查位置或无线环境是否发生变化。"],
    "finding.raw.title": ["원시 IE 미제공", "Raw IEs unavailable", "未提供原始 IE"],
    "finding.raw.detail": ["이 스캔에서 AP의 Information Element가 반환되지 않았습니다.", "No information element data was returned for this AP in this scan.", "此次扫描未返回此接入点的信息元素数据。"],
    "Hidden network": ["숨겨진 네트워크", "Hidden network", "隐藏网络"],
    "SSID unavailable": ["이름 미제공", "Name unavailable", "名称不可用"]
]
